### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by Hai-sea** [yaocccc/nvim-foldsign#1]
我发现这个和我用的其他插件有冲突,于是我修改了
![2023-02-21_12-19](https://user-images.githubusercontent.com/118412770/220247991-dd44d2f3-bbb5-4697-9540-f1b40f1be5e3.png)
![2023-02-21_12-22](https://user-images.githubusercontent.com/118412770/220248007-3b819103-d14f-4bb0-a3ce-c952407847b5.png)

**Comment by Hai-sea** [comment]
{ virt_text_win_col = -1 - M.numberwidth, virt_text = { { sign, "FoldColumn" } } }

**Comment by yaocccc** [comment]
麻烦请确认一下
  :echo &signcolumn &numberwidth

**Comment by yaocccc** [comment]
我先加一个可自定义offset的配置

**Comment by Hai-sea** [comment]
![2023-02-21_13-55](https://user-images.githubusercontent.com/118412770/220259528-ec7dfb38-c38c-4e55-ac05-e43972fa4d9d.png)

**Comment by yaocccc** [comment]
我想，可能只是单纯粹有bug，汗

**Comment by yaocccc** [comment]
我新提交了一个修复commit，现在应该完全对了
